name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]
# Allow manual trigger 
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_NAME: 'fn-helloworld'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'fn-helloworld'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  LOAD_TESTING_NAME: 'lt-temp'
  LOAD_TESTING_SCRIPT: './alt-scripts/test.yaml'

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

     #If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh # For Linux, use bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        
    - name: Azure Load Testing
      uses: Azure/load-testing@v1
      with:
         # Path of the YAML file. Should be fully qualified path or relative to the default working directory
         loadtestConfigFile: ${{ env.LOAD_TESTING_SCRIPT }}
         # Enter or Select the name of an existing Azure Load Testing resource
         loadtestResource: ${{ env.LOAD_TESTING_NAME }}
         # Enter or Select the Azure Resource Group that contains the Load test resource specified above
         resourceGroup: 'rg-demos'         
