name: Branching-create-iac
on:
   create
jobs:
   Run_IAC_for_new_branch:
      name: 'Running IAC for new Branch'
      runs-on: ubuntu-latest
      if: ${{contains(github.ref, 'refs/heads/releases/')}}
      steps:
         - name: Setting Branch Name to Variable
           run: |
            # Short name for current branch. For PRs, use target branch (base ref)
            echo "BRANCH_NAME=$(echo $GITHUB_REF | cut -d'/' -f 4)" >> $GITHUB_ENV
         
         - name: 'Setting IAC for new branch'
           run: |
            echo ${{ env.BRANCH_NAME }}
         - uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              enable-AzPSSession: true

         - name: Install ADE extension
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az extension add --name devcenter --upgrade
               
         - name: Register DevCenter
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az provider register --namespace Microsoft.DevCenter
               
         #- name: test
         #  uses: azure/powershell@v1
         #  with:
         #    azPSVersion: "3.1.0"
         #    inlineScript: |
         #      az account set --subscription ME-MngEnvMCAP969004-bryanfoster-1
         #      $DEVCID= $(az devcenter admin devcenter show -n dc-main-2 --resource-group rg-developer_landing_zone --query id -o tsv)
         #      echo $DEVCID

         - name: Create DLZ Project
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
               az devcenter admin project create --name 'newproject-${{ env.BRANCH_NAME }}-dev' --resource-group 'rg-developer_landing_zone' --location 'westus3' --dev-center-id ${{ secrets.DEVCENTERID }}
               
         - name: Create Owner for DLZ Project, Get Roles
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
              az role assignment create --assignee ${{ secrets.DEVCENTER_SERVICEPRINCIPLE_OWNER_ID }} --role "Owner" --scope "/subscriptions/${{ secrets.DEVCENTER_SUBID }}"
         
         - name: Create Project Environment Type for new branch which will allow environments to be built against
           uses: azure/powershell@v1
           with:
             azPSVersion: "3.1.0"
             inlineScript: |
              az devcenter admin project-environment-type create `
              --deployment-target-id  "subscriptions/${{ secrets.DEVCENTER_SUBID }}" `
              --location "westus3" `
              --identity-type "SystemAssigned" `
              --environment-type-name "Development" `
              --project-name "newproject-${{ env.BRANCH_NAME }}-dev" `
              --status "Enabled" `
              --resource-group "rg-developer_landing_zone"


         #This will create an deployed Environments of the project and environment type from above.           
         #- name: Create devCenter Project Env Typ
         #  uses: azure/powershell@v1
         #  with:
         #    azPSVersion: "3.1.0"
         #    inlineScript: |
         #      az devcenter dev environment create `
         #      --endpoint 'https://54d63bdf-d817-4fa5-a99a-0ec5f32c518c-dc-main-2.westus3.devcenter.azure.com/' `
         #      --project-name "newproject-${{ env.BRANCH_NAME }}-dev" `
         #      --catalog-name "MainProjects" `
         #      --environment-definition-name "Podcast_Web_App" `
         #      --environment-type "Testing"     

              
              
         
               
               
